# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-03 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablefor2', '0037_auto_20190528_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupavailability',
            name='matched_group_users',
            field=models.TextField(null=True),
        ),
    ]
