# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-24 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablefor2', '0037_auto_20190528_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='what_is_your_favorite_movie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='what_is_your_favorite_movie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
