# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablefor2', '0038_auto_20190624_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
